name: 'Terratest GitHub Actions'
on:
  pull_request:
    branches:
      - master
    types: [labeled]

jobs:
  Terratest:
    name: 'Terratest for basic'
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: Configure AWS Credentials
        uses: clouddrove/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-2

      - name: 'Terratest'
        if: ${{ github.event.label.name == 'terratest' }}
        uses: 'clouddrove/github-actions@v6.0'
        with:
          actions_subcommand: 'terratest'
          tf_actions_working_dir: '_test/basic'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Slack Notification'
        uses: clouddrove/action-slack@v2
        with:
          status: ${{ job.status }}
          fields: repo,author
          author_name: 'CloudDrove'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }} # required
        if: always()
