---
name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  tf-checks-complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.9
    with:
      working_directory: './_examples/complete/'
  tf-checks-basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.0.9
    with:
      working_directory: './_examples/vpc_link_api/'
...
